name: ParamsTest
on:
  workflow_dispatch: ~

env:
  BICEP_PARAMS_JSON: ${{ secrets.BICEP_PARAMETERS_JSON }}
  BICEP_PARAMS_STRING: ${{ secrets.BICEP_PARAMETERS_STRING }}
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./PortalResources.bicep
        parameters: ${{ env.BICEP_PARAMS }}
        failOnStdErr: false
